name: CI_CD
on:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x.x'
      - name: Build the project
        run: dotnet build -c Release
      - name: Test the project
        run: dotnet test
      - name: publish
        run: dotnet publish -c Release -o ./output
      - name: zip the result
        run: zip -r ../output.zip .
        working-directory: ./output
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.zip
  CD:
    needs: CI
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: output
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with:
          app-name: PlainGitHubActionsDemo
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: output.zip