name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x.x'
      - name: Build the project
        run: dotnet build -c Release
      - name: Test the project
        run: dotnet test